# Generated by Django 2.2.11 on 2020-04-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasenc',
            options={'verbose_name': 'Encabezado Compra', 'verbose_name_plural': 'Encabezado Compras'},
        ),
    ]
