# Generated by Django 2.2.11 on 2020-03-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_unidadmedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='descripcion',
            field=models.CharField(help_text='Descripcion de la Unidad de Medida', max_length=100, unique=True),
        ),
    ]
